### ISSUE TITLE
Option to stop displaying the "No density map during MD" warning dialog

### ISSUE THREAD

**Issue by ajasja** [tristanic/isolde#5]
ISODE looks extremely impressive!
I'm trying to leverage just a small subset of the functionality: I have a model with several domains connected with flexible loops. I'm trying to drag the domains around while in MD mode, however every time I start a simulation I get the following window:
![image](https://user-images.githubusercontent.com/19926/146901802-5661cb1c-af13-488d-829c-c9a84f011c57.png)

I appreciate the warning, but I think once is enough:) Would it be possible to add a checkbox (do not display this dialog in the future?)
Or another setting to turn it off?

**Comment by tristanic** [comment]
Glad you're liking ISOLDE!

Yep - that repeated warning annoys me too. The only reason I haven't added a "don't show me this again" checkbox is that first I have to add a persistent user settings framework... something that I more-or-less forgot about while putting the bigger pieces together. I have actually made a start on that, and as soon as I find a bit more quality coding time should be able to get it up and running pretty quickly.

**Comment by tristanic** [comment]
In ISOLDE 1.4, you'll have the option to suppress this warning for the remainder of a given session.

**Comment by ajasja** [comment]
Thanks!
