### ISSUE TITLE
Error during installation of 1.4b1 wheel

### ISSUE THREAD

**Issue by georgkempf** [tristanic/isolde#7]
I got the following error after
toolshed install ChimeraX_Clipper-0.18.0-cp39-cp39-macosx_10_13_x86_64.whl
toolshed install ChimeraX_ISOLDE-1.4b1-cp39-cp39-macosx_10_13_x86_64.whl

Error processing trigger "new frame":
ValueError: Didn't find section 'Main' in tab 'ISOLDE'

File "/Applications/ChimeraX-1.4.app/Contents/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/chimerax/ui/widgets/tabbedtoolbar.py", line 496, in set_enabled
raise ValueError(f"Didn't find section '{section_title}' in tab '{tab_title}'")

**Comment by tristanic** [comment]
Hmm... I think I know what's going on here - if I'm right, you started ISOLDE immediately after installing it? If so, it should work correctly after restarting ChimeraX. Problem is that the new top ribbon bar is only intialised on ChimeraX startup, and I don't think I'm able to change that. Will check with the ChimeraX devs to see if it can be done - and if not, if there is a way to add a "restart ChimeraX before using" message to the installation.

**Comment by georgkempf** [comment]
The error occurred first during installation and then when trying to open Isolde. Restarting ChimeraX indeed solved the issue!

**Comment by tristanic** [comment]
Great to know - and thanks for reporting!

**Comment by tristanic** [comment]
Fixed - ISOLDE will now bring up a "please restart ChimeraX" dialog on first install. For future ChimeraX versions the underlying bug should be fixed, so a restart will not be necessary.
