### ISSUE TITLE
Loading maps ChimeraX_ISOLDE-1.4b1-cp39-cp39-manylinux_2_17_x86_64

### ISSUE THREAD

**Issue by frozenfas** [tristanic/isolde#8]
When I am using the gui to add maps to a working model, it seems to add the map at the bottom of the list regardless of which map I select.

**Comment by tristanic** [comment]
Whoops! I can see exactly what went wrong there (boneheaded mistake when generating callbacks). Fixed in the code, and will be in the release (or next beta, if I do another one first). In the meantime, you can get the result you want with the command "clipper assoc #{map id} to #{model id}".

**Comment by frozenfas** [comment]
thanks :) That's what betas are for :)
